---
apiVersion: "plugin.halo.run/v1alpha1"
kind: "Plugin"
metadata:
  name: "PluginCaptcha"
spec:
  enabled: true
  requires: ">=2.20.0"
  author:
    name: "Beibing"
    website: "https://github.com/beibing173/plugin-captcha"
  logo: "logo.png"
  displayName: "人机验证"
  description: "为 Halo 登录和注册页面加入人机验证，支持极验 Geetest、Cloudflare Turnstile、本地图形验证码，有效防止暴力破解和恶意登录。"
  license:
  - name: "MIT"
    url: "https://github.com/beibing173/plugin-captcha/blob/main/LICENSE"
  repo: "https://github.com/beibing173/plugin-captcha"
  issues: "https://github.com/beibing173/plugin-captcha/issues"
  website: ""
  settingName: "captcha-setting"
  configMapName: "captcha-config"
  version: "1.0.0"
